### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jklukas** [mdub/withenv#1]
@mdub - I found this project last week and it inspired me to create a substantially revised version with support for GPG-encrypted files, zsh, and more comprehensive completion (https://github.com/jklukas/withenv). It changes the interface (in particular, it drops the hiding of file extensions), so I'm guessing you wouldn't want to directly pull it into your project.

Do you intend for this project to be available for derivative works? I'd like to put an MIT-style license on my fork and mention in the license that the code is based on https://github.com/mdub/withenv. Does that sound good? Would you have other wishes?

**Comment by mdub** [comment]
@jklukas oh, nice.  I look forward to checking out your fork.

What your suggest re licensing sounds fine to me. 

FWIW, I've dropped a `LICENSE` file into my repo (50be1ff5f4e6f370e4548456e88a85cd5abe42e6)

**Comment by jklukas** [comment]
Thanks for adding the license. My fork is now "live" in the sense that I use it in my day-to-day work and it's functioning well for my purposes, so feel free to look it over and take any code/ideas that are useful to you.

I learned several things from reading and modifying your code, so thanks for putting this out there.
